[package]
name = "tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
leptos_router = "0.8.11"
leptos_meta = "0.8.5"
wasm-bindgen = "0.2"
log = "0.4"
console_error_panic_hook = "0.1"

